import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView } from 'react-native';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

interface Section {
  id: string;
  title: string;
  content: string;
}

const sections: Section[] = [
  {
    id: 'intro',
    title: '',
    content: `Welcome to the Smart Commerce website and/ or any and/or all associated mobile application(s) (the "Site"). The Site is provided by Amazon Smart Commerce Solutions Private Limited ("ASCSPL" or "we" or "us" or "our"), with its registered office at H-9, Block B-1, Mohan Cooperative Industrial Area, Mathura Road, New Delhi -110044.

The Site is provided subject to the conditions contained herein. Please read these terms of use of the Site ("Terms of Use") carefully. By visiting the Site, you signify your agreement to be bound by these conditions. If you do not agree to all of these Terms of Use, please do not use this Site. Also, when you use any current or future ASCSPL service or business, you also will be subject to the guidelines, terms and agreements applicable to such service or business.

These Terms of Use constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.`,
  },
  {
    id: 'privacy',
    title: 'Privacy:',
    content: `Please review our Privacy Notice, which also governs your visit to this Site, to understand our practices.`,
  },
  {
    id: 'electronic',
    title: 'Electronic Communications:',
    content: `When you visit the Site or send e-mails to us, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this Site. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.`,
  },
  {
    id: 'copyright',
    title: 'Copyright:',
    content: `All content included on this Site, such as text, graphics, logos, button icons, images, videos, audio clips, digital downloads, data compilations, and software, is the property of ASCSPL or its affiliates or its content suppliers and protected by United States, Luxembourg, United Kingdom, India and international copyright laws.

The compilation of all content on this Site is the exclusive property of ASCSPL or its affiliates and protected by United States, Luxembourg, United Kingdom, India and international copyright laws.

All software used on this Site is the property of ASCSPL, its affiliates or its software suppliers and protected by United States, Luxembourg, United Kingdom, India and international copyright laws.

You may not systematically extract/ or re-utilise parts of the contents of the Site without ASCSPL and / or its affiliate's (as may be applicable) express written consent. In particular, you may not utilise any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation of any substantial parts of this Site, without ASCSPL and / or its affiliate's (as may be applicable) express written consent.`,
  },
  {
    id: 'trademarks',
    title: 'Trademarks:',
    content: `ASCSPL, the ASCSPL logo, and other marks indicated on our Site are trademarks of ASCSPL or its affiliates in the United States and other countries.

Other ASCSPL graphics, logos, page headers, button icons, scripts, and service names are trademarks or trade dress of ASCSPL or its affiliates. ASCSPL and its affiliates' trademarks and trade dress may not be used in connection with any product or service that is not ASCSPL or its affiliates' as applicable, in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits ASCSPL or its affiliates. All other trademarks not owned by ASCSPL or its affiliates that appear on this Site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by ASCSPL or its affiliates.`,
  },
  {
    id: 'license',
    title: 'License and Site access:',
    content: `ASCSPL grants you a limited license to access and make personal use of this Site and not to download (other than page caching) or modify it, or any portion of it, except with express written consent of ASCSPL and / or its affiliates, as may be applicable.

This license does not include any resale or commercial use of this Site or its contents; any derivative use of this Site or its contents; or any use of data mining, robots, or similar data gathering and extraction tools.

This Site or any portion of this Site (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of ASCSPL and / or its affiliates, as may be applicable.

You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of ASCSPL or its affiliates without their express written consent. You may not use any meta tags or any other "hidden text" utilizing ASCSPL's or its affiliates name or trademarks without their express written consent. Any unauthorized use terminates the permission or license granted by ASCSPL and / or its affiliates. You may not use any logo or other proprietary graphic or trademark of ASCSPL or its affiliates as part of the link without their express written permission.`,
  },
  {
    id: 'activity',
    title: 'Your activity:',
    content: `Your activity on the Site is not intended for use by children. If you are a minor, i.e. under the age of 18 years, you may use the Site only with involvement of a parent or guardian. ASCSPL and its affiliates reserve the right to refuse service, terminate accounts, or remove or edit content in their sole discretion.

You must not use the Site in any way that causes, or is likely to cause, the Site or access to it to be interrupted, damaged or impaired in any way. You understand that you, and not ASCSPL, are responsible for all electronic communications and content sent from your computer to us and you must use the Site for lawful purposes only.

You must not use the Site in any way that causes, or is likely to cause, the Site or access to it to be interrupted, damaged or impaired in any way. You understand that you, and not ASCSPL, are responsible for all electronic communications and content sent from your computer to us and you must use the Site for lawful purposes only and only in accordance with the applicable law. You must not use the Site for any of the following:

a) for fraudulent purposes, or in connection with a criminal offence or other unlawful activity;

b) to send, use or reuse any material that is illegal, offensive, (including but not limited to material that is sexually explicit or which promotes racism, bigotry, hatred or physical harm), abusive, harassing, misleading, indecent, defamatory, disparaging, obscene or menacing; or in breach of copyright, trademark, confidentiality, privacy or any other proprietary information or right; or is otherwise injurious to third parties; or objectionable or otherwise unlawful in any manner whatsoever; or which consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any "spam"; and

c) to cause annoyance, inconvenience or needless anxiety.`,
  },
  {
    id: 'yourlicense',
    title: 'Your license:',
    content: `If you submit material, and unless we indicate otherwise you grant ASCSPL and its affiliates a non-exclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant ASCSPL and its affiliates and sub-licensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content or material that you post or submit or that you otherwise provide on or through the Site; that the content is accurate; that the content is lawful; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify ASCSPL and its affiliates for all claims arising from content you supply. ASCSPL has the right but not the obligation to monitor and edit or remove any activity or content. ASCSPL takes no responsibility and assumes no liability for any content submitted by you or any third party.`,
  },
  {
    id: 'services',
    title: 'Services description:',
    content: `ASCSPL and its affiliates attempt to be as accurate as possible. However, ASCSPL does not warrant that descriptions of or other content of this Site is accurate, complete, reliable, current, or error-free. Also, your access to the Site may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services without notice. We will attempt to limit the frequency and duration of any such suspension or restriction. ASCSPL does not make any representations or provide any warranties or guarantees of any kind about the Site and the products and services offered on such Site. ASCSPL is not liable for the unavailability of any products and services offered on such Site.

ASCSPL has no control over and accepts no responsibility for adverts contained on the Site. If you agree to purchase goods and/ or services from any third party who advertises on the Site, you do so at your own risk. The advertiser, not ASCSPL, is the seller of those goods and/ or services and is responsible for such goods and/ or services. ASCSPL does not endorse, and is not responsible or liable for any content, advertising, products, services or other materials on, or available from, such sites or resources.`,
  },
  {
    id: 'indemnity',
    title: 'Indemnity and release:',
    content: `You shall indemnify and hold harmless ASCSPL, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use or any document incorporated by reference, or your violation of any law, rules, regulations or the rights of a third party or out of any material, data or information uploaded, posted, transmitted or otherwise made available by you on the Site or through our services.`,
  },
  {
    id: 'relationship',
    title: 'Relationship of parties:',
    content: `You and ASCSPL are independent contractors, and nothing in this Terms of Use will be construed to create a partnership, joint venture, association of persons, agency, franchise, sales representative, or employment relationship between the parties. You will have no authority to make or accept any offers or representations on our behalf. You will not make any statement that would contradict anything contemplated in this section. This Terms of Use will not create an exclusive relationship between you and us.`,
  },
  {
    id: 'disclaimer',
    title: 'Disclaimer:',
    content: `THIS SITE IS PROVIDED BY ASCSPL ON AN "AS IS" AND "AS AVAILABLE" BASIS. ASCSPL MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS SITE OR THE INFORMATION, CONTENT, MATERIALS, OR PRODUCTS INCLUDED ON THIS SITE. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE IS AT YOUR SOLE RISK. ASCSPL RESERVES THE RIGHT TO WITHDRAW OR DELETE ANY INFORMATION FROM THIS SITE AT ANY TIME IN ITS DISCRETION.

TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, ASCSPL DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. ASCSPL DOES NOT WARRANT THAT THIS SITE, ITS SERVERS, OR E-MAIL SENT FROM ASCSPL ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ASCSPL WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THIS SITE, INCLUDING, BUT NOT LIMITED TO INDIRECT, INCIDENTAL, PUNITIVE AND CONSEQUENTIAL DAMAGES.`,
  },
  {
    id: 'governing',
    title: 'Governing law:',
    content: `By visiting this Site, you agree that the laws of India will govern these Terms of Use and any dispute of any sort that might arise between you and ASCSPL or its affiliates.`,
  },
  {
    id: 'disputes',
    title: 'Disputes:',
    content: `Any dispute relating in any way to your visit to this Site shall be submitted to the exclusive jurisdiction of the courts at New Delhi, India.`,
  },
  {
    id: 'waiver',
    title: 'Waiver:',
    content: `If you breach these Terms of Use and we take no action, we will still be entitled to use our rights and remedies in any other situation where you breach these Terms of Use.`,
  },
  {
    id: 'events',
    title: 'Events beyond our reasonable control:',
    content: `We will not be held responsible for any delay or failure to comply with our obligations under these Terms of Use if the delay or failure arises from any cause which is beyond our reasonable control. This condition does not affect your statutory rights.`,
  },
  {
    id: 'policies',
    title: 'Site policies, modification and severability:',
    content: `Please review our other policies on this Site. These policies also govern your visit to the Site. We reserve the right to make changes to our Site, policies, and these Terms of Use at any time. If any of these conditions shall be deemed invalid, void, or for any reason unenforceable, that condition shall be deemed severable and shall not affect the validity and enforceability of any remaining conditions.`,
  },
  {
    id: 'contact',
    title: 'Contact us:',
    content: `If you would like to ask about, make a request relating to, or complain about your use and/ or access of the site, please e-mail us at smartcommerce-grievanceofficer@amazon.com`,
  },
];

export default function TermsScreen({ onBack }: { onBack: () => void }) {
  const sectionTitles = [
    'Privacy',
    'Electronic communcations',
    'Copyright',
    'Trademarks',
    'License and Site access',
    'Your activity',
    'Your License',
    'Services description',
    'Indemnity and release',
    'Relationship of parties',
    'Disputes',
    'Waiver',
    'Events beyond our reasonable control',
    'Site policies, modification and severability',
    'Contact us',
  ];

  return (
    <View style={{ flex: 1, backgroundColor: '#fff5f8' }}>
      <View style={styles.header}>
        <TouchableOpacity onPress={onBack}>
          <MaterialCommunityIcons name="arrow-left" size={28} color="#ffffff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Use</Text>
        <View style={{ width: 28 }} />
      </View>

      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        {/* Banner */}
        <View style={styles.banner}>
          <View style={styles.bannerOverlay} />
          <Text style={styles.bannerText}>Terms of use</Text>
        </View>

        {/* Section Links List */}
        <View style={styles.sectionsList}>
          <Text style={styles.listTitle}>Privacy</Text>
          {sectionTitles.map((title, index) => (
            <Text key={index} style={styles.sectionLinkText}>{title}</Text>
          ))}
        </View>

        {/* Full Content */}
        {sections.map((section, index) => (
          <View key={section.id} style={styles.contentSection}>
            {section.title && <Text style={styles.sectionHeading}>{section.title}</Text>}
            <Text style={styles.sectionText}>{section.content}</Text>
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer}>
          <View style={styles.socialIcons}>
            <TouchableOpacity style={styles.socialIcon}>
              <MaterialCommunityIcons name="instagram" size={20} color="#1a1a1a" />
            </TouchableOpacity>
            <TouchableOpacity style={styles.socialIcon}>
              <MaterialCommunityIcons name="facebook" size={20} color="#1a1a1a" />
            </TouchableOpacity>
            <TouchableOpacity style={styles.socialIcon}>
              <MaterialCommunityIcons name="youtube" size={20} color="#1a1a1a" />
            </TouchableOpacity>
          </View>
          <View style={styles.logoContainer}>
            <Text style={styles.logoText}>smartcommerce</Text>
            <Text style={styles.logoSubtext}>SmartBiz Sakhi store</Text>
          </View>
          <View style={styles.footerInfo}>
            <Text style={styles.footerText}>Built in</Text>
            <Text style={styles.flag}>🇮🇳</Text>
          </View>
          <Text style={styles.copyright}>
            © 2025 SmartBiz Sakhi store. All rights reserved
          </Text>
          <View style={styles.footerLinks}>
            <TouchableOpacity>
              <Text style={styles.footerLink}>Privacy policy</Text>
            </TouchableOpacity>
            <TouchableOpacity>
              <Text style={styles.footerLink}>Terms of use</Text>
            </TouchableOpacity>
            <TouchableOpacity>
              <Text style={styles.footerLink}>Sitemap</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 18,
    backgroundColor: '#e61580',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e4ec',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingBottom: 40,
  },
  banner: {
    height: 110,
    backgroundColor: '#e61580',
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  bannerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  bannerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    zIndex: 1,
  },
  sectionsList: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 20,
  },
  listTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 12,
  },
  sectionLinkText: {
    fontSize: 18,
    color: '#222',
    paddingVertical: 8,
    paddingLeft: 6,
  },
  contentSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 12,
  },
  sectionText: {
    fontSize: 16,
    color: '#222',
    lineHeight: 24,
    marginBottom: 8,
  },
  footer: {
    backgroundColor: '#1a1a2e',
    padding: 24,
    marginTop: 32,
    alignItems: 'center',
  },
  socialIcons: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 12,
  },
  socialIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  logoText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  logoSubtext: {
    fontSize: 14,
    color: '#fff',
  },
  footerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  footerText: {
    fontSize: 14,
    color: '#fff',
    marginRight: 8,
  },
  flag: {
    fontSize: 20,
  },
  copyright: {
    fontSize: 12,
    color: '#fff',
    marginBottom: 16,
    textAlign: 'center',
  },
  footerLinks: {
    flexDirection: 'row',
    gap: 16,
  },
  footerLink: {
    fontSize: 14,
    color: '#fff',
    textDecorationLine: 'underline',
  },
});
